/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfacesGráficas;

import java.awt.Color;

/**
 *
 * @author nikos
 */
public class Intro extends javax.swing.JFrame {

    /**
     * Creates new form Intro
     */
    public Intro() {
        this.setLocation(350,200);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnCrearEnter = new javax.swing.JLabel();
        jValvulaEnt = new javax.swing.JLabel();
        jFacturaEnt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jExit = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        MenuPrincipal = new javax.swing.JLabel();
        jFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 400));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnCrearEnter.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jBtnCrearEnter.setForeground(new java.awt.Color(255, 255, 255));
        jBtnCrearEnter.setText("Personas");
        jBtnCrearEnter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCrearEnterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnCrearEnterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnCrearEnterMouseExited(evt);
            }
        });
        jPanel1.add(jBtnCrearEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jValvulaEnt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jValvulaEnt.setForeground(new java.awt.Color(255, 255, 255));
        jValvulaEnt.setText("Válvulas");
        jValvulaEnt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jValvulaEntMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jValvulaEntMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jValvulaEntMouseExited(evt);
            }
        });
        jPanel1.add(jValvulaEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        jFacturaEnt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jFacturaEnt.setForeground(new java.awt.Color(255, 255, 255));
        jFacturaEnt.setText("Facturas");
        jFacturaEnt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFacturaEntMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jFacturaEntMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jFacturaEntMouseExited(evt);
            }
        });
        jPanel1.add(jFacturaEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/images.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 100));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jExit.setBackground(new java.awt.Color(51, 51, 255));
        jExit.setFont(new java.awt.Font("SWTxt", 0, 24)); // NOI18N
        jExit.setForeground(new java.awt.Color(255, 255, 255));
        jExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jExit.setText("X");
        jExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jExitMouseExited(evt);
            }
        });
        jPanel2.add(jExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 30, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ValvulaBásica.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 170, 400));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ValvulaRetenedora.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FacturaIcono.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 110, -1));

        MenuPrincipal.setFont(new java.awt.Font("Thames", 0, 36)); // NOI18N
        MenuPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        MenuPrincipal.setText("Menu Principal");
        jPanel1.add(MenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aZUL.jpg"))); // NOI18N
        jPanel1.add(jFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCrearEnterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCrearEnterMouseClicked
        jCrear ventana = new jCrear();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnCrearEnterMouseClicked

    private void jBtnCrearEnterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCrearEnterMouseEntered
        jBtnCrearEnter.setForeground(Color.green);
    }//GEN-LAST:event_jBtnCrearEnterMouseEntered

    private void jBtnCrearEnterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCrearEnterMouseExited
        jBtnCrearEnter.setForeground(Color.white);
    }//GEN-LAST:event_jBtnCrearEnterMouseExited

    private void jExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExitMouseEntered
        jExit.setForeground(Color.red);
    }//GEN-LAST:event_jExitMouseEntered

    private void jExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExitMouseExited
        jExit.setForeground(Color.white);
    }//GEN-LAST:event_jExitMouseExited

    private void jExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jExitMouseClicked

    private void jValvulaEntMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jValvulaEntMouseEntered
        jValvulaEnt.setForeground(Color.CYAN);
    }//GEN-LAST:event_jValvulaEntMouseEntered

    private void jValvulaEntMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jValvulaEntMouseExited
        jValvulaEnt.setForeground(Color.white);
    }//GEN-LAST:event_jValvulaEntMouseExited

    private void jFacturaEntMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFacturaEntMouseEntered
        jFacturaEnt.setForeground(Color.YELLOW);
    }//GEN-LAST:event_jFacturaEntMouseEntered

    private void jFacturaEntMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFacturaEntMouseExited
        jFacturaEnt.setForeground(Color.white);
    }//GEN-LAST:event_jFacturaEntMouseExited

    private void jValvulaEntMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jValvulaEntMouseClicked
        jValvulas valvulas = new jValvulas();
        valvulas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jValvulaEntMouseClicked

    private void jFacturaEntMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFacturaEntMouseClicked
        jFactura ventana = new jFactura();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jFacturaEntMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Intro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MenuPrincipal;
    private javax.swing.JLabel jBtnCrearEnter;
    private javax.swing.JLabel jExit;
    private javax.swing.JLabel jFacturaEnt;
    private javax.swing.JLabel jFondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jValvulaEnt;
    // End of variables declaration//GEN-END:variables
}
