/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfacesGráficas;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javaapplication1.Cliente;
import javaapplication1.Empleado;
import javaapplication1.Persona;
import javax.swing.JOptionPane;

/**
 *
 * @author nikos
 */
public class jCrear extends javax.swing.JFrame {

    /**
     * Creates new form jCrear
     */
    ArrayList<Cliente> listaClientes = new ArrayList<>();
    ArrayList<Empleado> listaEmpleados = new ArrayList<>();
    public jCrear() {
        this.setLocation(350,200);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelExit = new javax.swing.JPanel();
        jExit = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        JClienteCrear = new javax.swing.JPanel();
        PanelInterno1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCntNombre = new javax.swing.JTextField();
        jClntEdad = new javax.swing.JTextField();
        jCntApellido = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        Limpiar = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jAñadirBtn = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        Cliente cliente = new Cliente();
        jTablaClientes = new javax.swing.JTable();
        jActualizarC = new javax.swing.JLabel();
        jEmpleadoCrear = new javax.swing.JPanel();
        PanelInterno2 = new javax.swing.JPanel();
        jActualizarE = new javax.swing.JLabel();
        jAñadirBtn2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jEmpNombre = new javax.swing.JTextField();
        jEmpApellido = new javax.swing.JTextField();
        jEmpEdad = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        Limpiar1 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablaEmpleados = new javax.swing.JTable();
        JNavegador = new javax.swing.JPanel();
        jInicio1 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jValvulas = new javax.swing.JLabel();
        jFacturas = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelExit.setBackground(new java.awt.Color(0, 0, 0));

        jExit.setFont(new java.awt.Font("SWTxt", 0, 24)); // NOI18N
        jExit.setForeground(new java.awt.Color(255, 255, 255));
        jExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jExit.setText("X");
        jExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelExitLayout = new javax.swing.GroupLayout(jPanelExit);
        jPanelExit.setLayout(jPanelExitLayout);
        jPanelExitLayout.setHorizontalGroup(
            jPanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelExitLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jExit)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelExitLayout.setVerticalGroup(
            jPanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelExitLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jExit)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 30, 40));

        JClienteCrear.setBackground(new java.awt.Color(0, 0, 0));

        PanelInterno1.setBackground(new java.awt.Color(0, 0, 0));
        PanelInterno1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Thames", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre");
        PanelInterno1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, 30));

        jLabel6.setFont(new java.awt.Font("Thames", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Apellido");
        PanelInterno1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 20));

        jLabel7.setFont(new java.awt.Font("Thames", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Edad");
        PanelInterno1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jCntNombre.setBackground(new java.awt.Color(0, 0, 0));
        jCntNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCntNombre.setForeground(new java.awt.Color(255, 255, 255));
        jCntNombre.setBorder(null);
        jCntNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCntNombreActionPerformed(evt);
            }
        });
        PanelInterno1.add(jCntNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 190, -1));

        jClntEdad.setBackground(new java.awt.Color(0, 0, 0));
        jClntEdad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jClntEdad.setForeground(new java.awt.Color(255, 255, 255));
        jClntEdad.setBorder(null);
        jClntEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClntEdadActionPerformed(evt);
            }
        });
        jClntEdad.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jClntEdadPropertyChange(evt);
            }
        });
        jClntEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jClntEdadKeyTyped(evt);
            }
        });
        PanelInterno1.add(jClntEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 190, -1));

        jCntApellido.setBackground(new java.awt.Color(0, 0, 0));
        jCntApellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCntApellido.setForeground(new java.awt.Color(255, 255, 255));
        jCntApellido.setBorder(null);
        jCntApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCntApellidoActionPerformed(evt);
            }
        });
        PanelInterno1.add(jCntApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 190, -1));
        PanelInterno1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 190, -1));
        PanelInterno1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 190, 10));
        PanelInterno1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 190, -1));

        Limpiar.setFont(new java.awt.Font("Thames", 0, 16)); // NOI18N
        Limpiar.setForeground(new java.awt.Color(255, 255, 255));
        Limpiar.setText("Limpiar");
        Limpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LimpiarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LimpiarMouseExited(evt);
            }
        });
        PanelInterno1.add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));
        PanelInterno1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 50, -1));

        jLabel3.setFont(new java.awt.Font("Thames", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Crear Clientes:");
        PanelInterno1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jAñadirBtn.setFont(new java.awt.Font("Thames", 0, 16)); // NOI18N
        jAñadirBtn.setForeground(new java.awt.Color(255, 255, 255));
        jAñadirBtn.setText("Añadir");
        jAñadirBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAñadirBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jAñadirBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jAñadirBtnMouseExited(evt);
            }
        });
        PanelInterno1.add(jAñadirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));
        PanelInterno1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 50, -1));

        jTablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "Edad"
            }
        ));
        jScrollPane1.setViewportView(jTablaClientes);

        PanelInterno1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 260, 350));

        jActualizarC.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jActualizarC.setForeground(new java.awt.Color(255, 255, 255));
        jActualizarC.setText("actualizar tabla");
        jActualizarC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jActualizarCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jActualizarCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jActualizarCMouseExited(evt);
            }
        });
        PanelInterno1.add(jActualizarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        javax.swing.GroupLayout JClienteCrearLayout = new javax.swing.GroupLayout(JClienteCrear);
        JClienteCrear.setLayout(JClienteCrearLayout);
        JClienteCrearLayout.setHorizontalGroup(
            JClienteCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelInterno1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JClienteCrearLayout.setVerticalGroup(
            JClienteCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelInterno1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Clientes", JClienteCrear);

        jEmpleadoCrear.setBackground(new java.awt.Color(0, 0, 0));

        PanelInterno2.setBackground(new java.awt.Color(0, 0, 0));
        PanelInterno2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jActualizarE.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jActualizarE.setForeground(new java.awt.Color(255, 255, 255));
        jActualizarE.setText("actualizar tabla");
        jActualizarE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jActualizarEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jActualizarEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jActualizarEMouseExited(evt);
            }
        });
        PanelInterno2.add(jActualizarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jAñadirBtn2.setFont(new java.awt.Font("Thames", 0, 16)); // NOI18N
        jAñadirBtn2.setForeground(new java.awt.Color(255, 255, 255));
        jAñadirBtn2.setText("Añadir");
        jAñadirBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAñadirBtn2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jAñadirBtn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jAñadirBtn2MouseExited(evt);
            }
        });
        PanelInterno2.add(jAñadirBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        jLabel2.setFont(new java.awt.Font("Thames", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Crear Empleados:");
        PanelInterno2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Thames", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre");
        PanelInterno2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, 30));

        jLabel8.setFont(new java.awt.Font("Thames", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Apellido");
        PanelInterno2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 20));

        jLabel10.setFont(new java.awt.Font("Thames", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Edad");
        PanelInterno2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jEmpNombre.setBackground(new java.awt.Color(0, 0, 0));
        jEmpNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jEmpNombre.setForeground(new java.awt.Color(255, 255, 255));
        jEmpNombre.setBorder(null);
        PanelInterno2.add(jEmpNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 190, -1));

        jEmpApellido.setBackground(new java.awt.Color(0, 0, 0));
        jEmpApellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jEmpApellido.setForeground(new java.awt.Color(255, 255, 255));
        jEmpApellido.setBorder(null);
        jEmpApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmpApellidoActionPerformed(evt);
            }
        });
        PanelInterno2.add(jEmpApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 190, -1));

        jEmpEdad.setBackground(new java.awt.Color(0, 0, 0));
        jEmpEdad.setFont(new java.awt.Font("Thames", 0, 14)); // NOI18N
        jEmpEdad.setForeground(new java.awt.Color(255, 255, 255));
        jEmpEdad.setBorder(null);
        jEmpEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmpEdadActionPerformed(evt);
            }
        });
        jEmpEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jEmpEdadKeyTyped(evt);
            }
        });
        PanelInterno2.add(jEmpEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 190, -1));
        PanelInterno2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 190, -1));
        PanelInterno2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 190, -1));
        PanelInterno2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 190, -1));

        Limpiar1.setFont(new java.awt.Font("Thames", 0, 16)); // NOI18N
        Limpiar1.setForeground(new java.awt.Color(255, 255, 255));
        Limpiar1.setText("Limpiar");
        Limpiar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Limpiar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Limpiar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Limpiar1MouseExited(evt);
            }
        });
        PanelInterno2.add(Limpiar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));
        PanelInterno2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 50, -1));
        PanelInterno2.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 50, 10));

        jTablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "Edad"
            }
        ));
        jScrollPane2.setViewportView(jTablaEmpleados);

        PanelInterno2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 260, 350));

        javax.swing.GroupLayout jEmpleadoCrearLayout = new javax.swing.GroupLayout(jEmpleadoCrear);
        jEmpleadoCrear.setLayout(jEmpleadoCrearLayout);
        jEmpleadoCrearLayout.setHorizontalGroup(
            jEmpleadoCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelInterno2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jEmpleadoCrearLayout.setVerticalGroup(
            jEmpleadoCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelInterno2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Empleado", jEmpleadoCrear);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 570, 310));

        JNavegador.setBackground(new java.awt.Color(0, 0, 0));
        JNavegador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInicio1.setFont(new java.awt.Font("Thames", 0, 18)); // NOI18N
        jInicio1.setForeground(new java.awt.Color(255, 255, 255));
        jInicio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jInicio1.setText("Inicio");
        jInicio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jInicio1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jInicio1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jInicio1MouseExited(evt);
            }
        });
        JNavegador.add(jInicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 50, -1));
        JNavegador.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 50, -1));

        jValvulas.setFont(new java.awt.Font("Thames", 0, 16)); // NOI18N
        jValvulas.setForeground(new java.awt.Color(255, 255, 255));
        jValvulas.setText("Valvulas");
        jValvulas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jValvulasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jValvulasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jValvulasMouseExited(evt);
            }
        });
        JNavegador.add(jValvulas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jFacturas.setFont(new java.awt.Font("Thames", 0, 16)); // NOI18N
        jFacturas.setForeground(new java.awt.Color(255, 255, 255));
        jFacturas.setText("Facturas");
        jFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFacturasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jFacturasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jFacturasMouseExited(evt);
            }
        });
        JNavegador.add(jFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));
        JNavegador.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 60, -1));
        JNavegador.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 60, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ValvulaBásica.png"))); // NOI18N
        JNavegador.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, -1, 90));

        jPanel1.add(JNavegador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 580, 80));

        jFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondonegro.jpg"))); // NOI18N
        jPanel1.add(jFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExitMouseEntered
        jExit.setForeground(Color.red);
    }//GEN-LAST:event_jExitMouseEntered

    private void jExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExitMouseExited
        jExit.setForeground(Color.white);
    }//GEN-LAST:event_jExitMouseExited

    private void jClntEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClntEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jClntEdadActionPerformed

    private void jCntApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCntApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCntApellidoActionPerformed

    private void jEmpEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmpEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmpEdadActionPerformed

    private void jEmpApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmpApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmpApellidoActionPerformed

    private void jCntNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCntNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCntNombreActionPerformed

    private void jExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jExitMouseClicked

    private void LimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LimpiarMouseClicked
        limpiar();
    }//GEN-LAST:event_LimpiarMouseClicked

    private void LimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LimpiarMouseEntered
        Limpiar.setForeground(Color.red);
    }//GEN-LAST:event_LimpiarMouseEntered

    private void LimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LimpiarMouseExited
        Limpiar.setForeground(Color.white);
    }//GEN-LAST:event_LimpiarMouseExited

    private void Limpiar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Limpiar1MouseClicked
        limpiarE();
    }//GEN-LAST:event_Limpiar1MouseClicked

    private void Limpiar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Limpiar1MouseEntered
        Limpiar1.setForeground(Color.red);
    }//GEN-LAST:event_Limpiar1MouseEntered

    private void Limpiar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Limpiar1MouseExited
        Limpiar1.setForeground(Color.white);
    }//GEN-LAST:event_Limpiar1MouseExited

    private void jAñadirBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAñadirBtnMouseEntered
        jAñadirBtn.setForeground(Color.green);
    }//GEN-LAST:event_jAñadirBtnMouseEntered

    private void jAñadirBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAñadirBtnMouseExited
        jAñadirBtn.setForeground(Color.white);
    }//GEN-LAST:event_jAñadirBtnMouseExited

    private void jAñadirBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAñadirBtnMouseClicked
        if (jCntNombre.getText().isBlank()|| jCntApellido.getText().isBlank() || jClntEdad.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Debe llenar todos los campos","Validar información",JOptionPane.INFORMATION_MESSAGE);
        } else{
            Cliente cliente = new Cliente(listaClientes.size()+1,jCntNombre.getText(),jCntApellido.getText(),Integer.parseInt(jClntEdad.getText()));
            listaClientes.add(cliente);
            
            mostrarClientes();
            limpiar();
        }
        
    }//GEN-LAST:event_jAñadirBtnMouseClicked
    public void mostrarClientes(){
        String matris[][] = new String[listaClientes.size()][4];
        for (int i = 0; i < listaClientes.size(); i++) {
            matris[i][0]=String.valueOf((listaClientes.get(i).getId()));
            matris[i][1]=listaClientes.get(i).getNombre();
            matris[i][2]=listaClientes.get(i).getApellido();
            matris[i][3]=String.valueOf(listaClientes.get(i).getEdad());
        }
        jTablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            matris,
            new String [] {
                "ID", "Nombre", "Apellido", "Edad"
            }
        ));
    }
    private void jClntEdadPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jClntEdadPropertyChange
       
    }//GEN-LAST:event_jClntEdadPropertyChange

    private void jClntEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jClntEdadKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9') && car!=(char)KeyEvent.VK_BACK_SPACE){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo se admiten números","Validar información",JOptionPane.INFORMATION_MESSAGE);
        } else if((car <'0' || car>'9') && car!=(char)KeyEvent.VK_BACK_SPACE){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo se admiten números","Validar información",JOptionPane.INFORMATION_MESSAGE);
        } 
    }//GEN-LAST:event_jClntEdadKeyTyped

    private void jAñadirBtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAñadirBtn2MouseClicked
        if (jEmpNombre.getText().isBlank()|| jEmpApellido.getText().isBlank() || jEmpEdad.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Debe llenar todos los campos","Validar información",JOptionPane.INFORMATION_MESSAGE);
        } else{
            Empleado empleado = new Empleado(listaEmpleados.size()+1,jEmpNombre.getText(),jEmpApellido.getText(),Integer.parseInt(jEmpEdad.getText()));
            listaEmpleados.add(empleado);
            
            mostrarEmpleado();
            limpiarE();
        }
    }//GEN-LAST:event_jAñadirBtn2MouseClicked
    public void mostrarEmpleado(){
        String matris[][] = new String[listaEmpleados.size()][4];
        for (int i = 0; i < listaEmpleados.size(); i++) {
            matris[i][0]=String.valueOf((listaEmpleados.get(i).getId()));
            matris[i][1]=listaEmpleados.get(i).getNombre();
            matris[i][2]=listaEmpleados.get(i).getApellido();
            matris[i][3]=String.valueOf(listaEmpleados.get(i).getEdad());
        }
        jTablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            matris,
            new String [] {
                "ID", "Nombre", "Apellido", "Edad"
            }
        ));
    }
    private void jAñadirBtn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAñadirBtn2MouseEntered
        jAñadirBtn2.setForeground(Color.green);
    }//GEN-LAST:event_jAñadirBtn2MouseEntered

    private void jAñadirBtn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAñadirBtn2MouseExited
        jAñadirBtn2.setForeground(Color.white);
    }//GEN-LAST:event_jAñadirBtn2MouseExited

    private void jEmpEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jEmpEdadKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9') && car!=(char)KeyEvent.VK_BACK_SPACE){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo se admiten números","Validar información",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jEmpEdadKeyTyped

    private void jActualizarCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jActualizarCMouseClicked
        mostrarClientes();
        for (Cliente persona : listaClientes) {
            System.out.println(persona.getNombre());
            
        }
    }//GEN-LAST:event_jActualizarCMouseClicked

    private void jActualizarEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jActualizarEMouseClicked
        mostrarEmpleado();
    }//GEN-LAST:event_jActualizarEMouseClicked

    private void jInicio1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInicio1MouseClicked
        Intro intro = new Intro();
        intro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jInicio1MouseClicked

    private void jInicio1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInicio1MouseEntered
        jInicio1.setForeground(Color.cyan);
    }//GEN-LAST:event_jInicio1MouseEntered

    private void jInicio1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInicio1MouseExited
        jInicio1.setForeground(Color.white);
    }//GEN-LAST:event_jInicio1MouseExited

    private void jValvulasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jValvulasMouseClicked
        jValvulas valvulas = new jValvulas();
        valvulas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jValvulasMouseClicked

    private void jValvulasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jValvulasMouseEntered
        jValvulas.setForeground(Color.red);
    }//GEN-LAST:event_jValvulasMouseEntered

    private void jValvulasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jValvulasMouseExited
        jValvulas.setForeground(Color.white);
    }//GEN-LAST:event_jValvulasMouseExited

    private void jFacturasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFacturasMouseEntered
        jFacturas.setForeground(Color.red);
    }//GEN-LAST:event_jFacturasMouseEntered

    private void jFacturasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFacturasMouseExited
        jFacturas.setForeground(Color.white);
    }//GEN-LAST:event_jFacturasMouseExited

    private void jActualizarCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jActualizarCMouseEntered
        jActualizarC.setForeground(Color.orange);
    }//GEN-LAST:event_jActualizarCMouseEntered

    private void jActualizarCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jActualizarCMouseExited
        jActualizarC.setForeground(Color.white);
    }//GEN-LAST:event_jActualizarCMouseExited

    private void jActualizarEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jActualizarEMouseEntered
        jActualizarE.setForeground(Color.yellow);
    }//GEN-LAST:event_jActualizarEMouseEntered

    private void jActualizarEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jActualizarEMouseExited
        jActualizarE.setForeground(Color.white);
    }//GEN-LAST:event_jActualizarEMouseExited

    private void jFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFacturasMouseClicked
        jFactura ventana = new jFactura();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jFacturasMouseClicked
    public void limpiar (){
        jCntNombre.setText("");
        jCntApellido.setText("");
        jClntEdad.setText("");
    }
    public void limpiarE(){
        jEmpEdad.setText("");
        jEmpApellido.setText("");
        jEmpNombre.setText("");
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JClienteCrear;
    private javax.swing.JPanel JNavegador;
    private javax.swing.JLabel Limpiar;
    private javax.swing.JLabel Limpiar1;
    private javax.swing.JPanel PanelInterno1;
    private javax.swing.JPanel PanelInterno2;
    private javax.swing.JLabel jActualizarC;
    private javax.swing.JLabel jActualizarE;
    private javax.swing.JLabel jAñadirBtn;
    private javax.swing.JLabel jAñadirBtn2;
    private javax.swing.JTextField jClntEdad;
    private javax.swing.JTextField jCntApellido;
    private javax.swing.JTextField jCntNombre;
    private javax.swing.JTextField jEmpApellido;
    private javax.swing.JTextField jEmpEdad;
    private javax.swing.JTextField jEmpNombre;
    private javax.swing.JPanel jEmpleadoCrear;
    private javax.swing.JLabel jExit;
    private javax.swing.JLabel jFacturas;
    private javax.swing.JLabel jFondo;
    private javax.swing.JLabel jInicio1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelExit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTablaClientes;
    private javax.swing.JTable jTablaEmpleados;
    private javax.swing.JLabel jValvulas;
    // End of variables declaration//GEN-END:variables
}