/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfacesGráficas;

import java.awt.Color;
import java.util.ArrayList;
import javaapplication1.Valvula;
import javaapplication1.Cliente;
import javaapplication1.Empleado;

/**
 *
 * @author nikos
 */

public class jFactura extends javax.swing.JFrame {

    /**
     * Creates new form jFactura
     */
    ArrayList<Valvula> listaV = new ArrayList<>();
    ArrayList<Cliente> listaC = new ArrayList<>();
    ArrayList<Empleado> listaE = new ArrayList<>();
    
    public jFactura() {
        initComponents();
        this.setLocation(350,200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JNavegador = new javax.swing.JPanel();
        jInicio1 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jValvulas = new javax.swing.JLabel();
        jFacturas = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        VistaClientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NombreC_txt = new javax.swing.JTextField();
        ApellidoC_txt = new javax.swing.JTextField();
        IdC_txt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        VistaEmpleados = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        IdE_txt = new javax.swing.JTextField();
        NombreE_txt = new javax.swing.JTextField();
        ApellidoE_txt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ReferV_txt = new javax.swing.JTextField();
        IdV_txt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        FacEmpleado = new javax.swing.JTextField();
        FacCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        IVA_Field = new javax.swing.JTextField();
        NoIva = new javax.swing.JTextField();
        TotalCompleto = new javax.swing.JTextField();
        jPanelExit = new javax.swing.JPanel();
        jExit = new javax.swing.JLabel();
        jFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JNavegador.setBackground(new java.awt.Color(0, 0, 0));
        JNavegador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInicio1.setFont(new java.awt.Font("Thames", 0, 18)); // NOI18N
        jInicio1.setForeground(new java.awt.Color(255, 255, 255));
        jInicio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jInicio1.setText("Inicio");
        jInicio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jInicio1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jInicio1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jInicio1MouseExited(evt);
            }
        });
        JNavegador.add(jInicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 50, -1));
        JNavegador.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 50, -1));

        jValvulas.setFont(new java.awt.Font("Thames", 0, 16)); // NOI18N
        jValvulas.setForeground(new java.awt.Color(255, 255, 255));
        jValvulas.setText("Valvulas");
        jValvulas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jValvulasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jValvulasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jValvulasMouseExited(evt);
            }
        });
        JNavegador.add(jValvulas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jFacturas.setFont(new java.awt.Font("Thames", 0, 16)); // NOI18N
        jFacturas.setForeground(new java.awt.Color(255, 255, 255));
        jFacturas.setText("Personas");
        jFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFacturasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jFacturasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jFacturasMouseExited(evt);
            }
        });
        JNavegador.add(jFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));
        JNavegador.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 60, -1));
        JNavegador.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 60, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ValvulaBásica.png"))); // NOI18N
        JNavegador.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, -1, 90));

        jPanel1.add(JNavegador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 580, 80));

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VistaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido"
            }
        ));
        jScrollPane2.setViewportView(VistaClientes);

        jPanel7.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 250, 140));

        jLabel1.setText("Buscar Clientes:");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Thames", 0, 12)); // NOI18N
        jLabel2.setText("ID");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 20, -1));

        jLabel3.setFont(new java.awt.Font("Thames", 0, 12)); // NOI18N
        jLabel3.setText("Nombre");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Thames", 0, 12)); // NOI18N
        jLabel4.setText("Apellido");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 20));
        jPanel7.add(NombreC_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 140, -1));
        jPanel7.add(ApellidoC_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 140, -1));
        jPanel7.add(IdC_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 140, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Buscar");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 50, 20));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Cliente", jPanel6);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VistaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido"
            }
        ));
        jScrollPane3.setViewportView(VistaEmpleados);

        jPanel9.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 250, 140));

        jLabel5.setText("Buscar Empleados:");
        jPanel9.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));
        jPanel9.add(IdE_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 140, -1));
        jPanel9.add(NombreE_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 140, -1));
        jPanel9.add(ApellidoE_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 140, -1));

        jLabel18.setFont(new java.awt.Font("Thames", 0, 12)); // NOI18N
        jLabel18.setText("ID");
        jPanel9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 20, -1));

        jLabel19.setFont(new java.awt.Font("Thames", 0, 12)); // NOI18N
        jLabel19.setText("Nombre");
        jPanel9.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel20.setFont(new java.awt.Font("Thames", 0, 12)); // NOI18N
        jLabel20.setText("Apellido");
        jPanel9.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 20));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Buscar");
        jPanel9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 50, 20));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Empleado", jPanel8);

        jPanel4.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 540, 170));

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Referencia", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel10.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 7, 250, 140));
        jPanel10.add(ReferV_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 140, -1));
        jPanel10.add(IdV_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 140, -1));

        jLabel10.setFont(new java.awt.Font("Thames", 0, 12)); // NOI18N
        jLabel10.setText("ID");
        jPanel10.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel11.setFont(new java.awt.Font("Thames", 0, 12)); // NOI18N
        jLabel11.setText("Referencia");
        jPanel10.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel12.setText("Buscar Válvulas:");
        jPanel10.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Buscar");
        jPanel10.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 50, 20));

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 540, 150));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Seleccionar", jPanel2);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Thames", 0, 14)); // NOI18N
        jLabel13.setText("Nombre cliente:");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel14.setFont(new java.awt.Font("Thames", 0, 14)); // NOI18N
        jLabel14.setText("Empleado a cargo:");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Referencia", "Cantidad", "Precio Unitario", "Total"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 510, 160));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FacturaIcono.png"))); // NOI18N
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        FacEmpleado.setEnabled(false);
        FacEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacEmpleadoActionPerformed(evt);
            }
        });
        jPanel5.add(FacEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 150, -1));

        FacCliente.setEnabled(false);
        FacCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacClienteActionPerformed(evt);
            }
        });
        jPanel5.add(FacCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 150, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("IVA( 19%)");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("TOTAL IVA");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 70, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("TOTAL SIN IVA");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 90, 20));

        IVA_Field.setEnabled(false);
        jPanel5.add(IVA_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 150, -1));

        NoIva.setEnabled(false);
        jPanel5.add(NoIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 180, -1));

        TotalCompleto.setEnabled(false);
        jPanel5.add(TotalCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 180, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Factura", jPanel3);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 560, 370));

        jPanelExit.setBackground(new java.awt.Color(0, 0, 0));

        jExit.setFont(new java.awt.Font("SWTxt", 0, 24)); // NOI18N
        jExit.setForeground(new java.awt.Color(255, 255, 255));
        jExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jExit.setText("X");
        jExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelExitLayout = new javax.swing.GroupLayout(jPanelExit);
        jPanelExit.setLayout(jPanelExitLayout);
        jPanelExitLayout.setHorizontalGroup(
            jPanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelExitLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jExit)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelExitLayout.setVerticalGroup(
            jPanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelExitLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jExit)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 30, 40));

        jFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondonegro.jpg"))); // NOI18N
        jPanel1.add(jFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jInicio1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInicio1MouseClicked
        Intro intro = new Intro();
        intro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jInicio1MouseClicked

    private void jInicio1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInicio1MouseEntered
        jInicio1.setForeground(Color.cyan);
    }//GEN-LAST:event_jInicio1MouseEntered

    private void jInicio1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInicio1MouseExited
        jInicio1.setForeground(Color.white);
    }//GEN-LAST:event_jInicio1MouseExited

    private void jValvulasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jValvulasMouseClicked
        jValvulas valvulas = new jValvulas();
        valvulas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jValvulasMouseClicked

    private void jValvulasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jValvulasMouseEntered
        jValvulas.setForeground(Color.red);
    }//GEN-LAST:event_jValvulasMouseEntered

    private void jValvulasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jValvulasMouseExited
        jValvulas.setForeground(Color.white);
    }//GEN-LAST:event_jValvulasMouseExited

    private void jFacturasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFacturasMouseEntered
        jFacturas.setForeground(Color.red);
    }//GEN-LAST:event_jFacturasMouseEntered

    private void jFacturasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFacturasMouseExited
        jFacturas.setForeground(Color.white);
    }//GEN-LAST:event_jFacturasMouseExited

    private void jExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jExitMouseClicked

    private void jExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExitMouseEntered
        jExit.setForeground(Color.red);
    }//GEN-LAST:event_jExitMouseEntered

    private void jExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExitMouseExited
        jExit.setForeground(Color.white);
    }//GEN-LAST:event_jExitMouseExited

    private void jFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFacturasMouseClicked
        jCrear ventana = new jCrear();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jFacturasMouseClicked

    private void FacEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FacEmpleadoActionPerformed

    private void FacClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FacClienteActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoC_txt;
    private javax.swing.JTextField ApellidoE_txt;
    private javax.swing.JTextField FacCliente;
    private javax.swing.JTextField FacEmpleado;
    private javax.swing.JTextField IVA_Field;
    private javax.swing.JTextField IdC_txt;
    private javax.swing.JTextField IdE_txt;
    private javax.swing.JTextField IdV_txt;
    private javax.swing.JPanel JNavegador;
    private javax.swing.JTextField NoIva;
    private javax.swing.JTextField NombreC_txt;
    private javax.swing.JTextField NombreE_txt;
    private javax.swing.JTextField ReferV_txt;
    private javax.swing.JTextField TotalCompleto;
    private javax.swing.JTable VistaClientes;
    private javax.swing.JTable VistaEmpleados;
    private javax.swing.JLabel jExit;
    private javax.swing.JLabel jFacturas;
    private javax.swing.JLabel jFondo;
    private javax.swing.JLabel jInicio1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelExit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel jValvulas;
    // End of variables declaration//GEN-END:variables
}
