/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfacesGráficas;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javaapplication1.ListaValvulas;
import javaapplication1.Valvula;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author nikos
 */
public class jValvulas extends javax.swing.JFrame {

    /**
     * Creates new form jValvulas
     */
    ArrayList<Valvula> listaV = new ArrayList<>();
    
    public jValvulas() {
        this.setLocation(350,200);
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jExit = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jVNombre = new javax.swing.JTextField();
        jVPrecio = new javax.swing.JTextField();
        jCodigo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jVCantidad = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jAñadirV = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jEditarPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CantidadEdit = new javax.swing.JTextField();
        PrecioEdit = new javax.swing.JTextField();
        RefeEditar = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jEditanBtn = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jRevisarPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jVRevisar = new javax.swing.JTable();
        JNavegador = new javax.swing.JPanel();
        jInicio1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPersonas = new javax.swing.JLabel();
        jFacturas = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jExit.setBackground(new java.awt.Color(51, 51, 255));
        jExit.setFont(new java.awt.Font("SWTxt", 0, 24)); // NOI18N
        jExit.setForeground(new java.awt.Color(255, 255, 255));
        jExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jExit.setText("X");
        jExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jExitMouseExited(evt);
            }
        });
        jPanel1.add(jExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 30, 40));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Thames", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Referencia");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Thames", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Precio");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        jLabel1.setFont(new java.awt.Font("Thames", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cantidad");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Thames", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Codigo");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ValvulaRetenedora.png"))); // NOI18N
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jVNombre.setBackground(new java.awt.Color(0, 0, 0));
        jVNombre.setFont(new java.awt.Font("Thames", 0, 16)); // NOI18N
        jVNombre.setForeground(new java.awt.Color(255, 255, 255));
        jVNombre.setBorder(null);
        jVNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVNombreActionPerformed(evt);
            }
        });
        jVNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jVNombreKeyTyped(evt);
            }
        });
        jPanel5.add(jVNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 150, -1));

        jVPrecio.setBackground(new java.awt.Color(0, 0, 0));
        jVPrecio.setFont(new java.awt.Font("Thames", 0, 16)); // NOI18N
        jVPrecio.setForeground(new java.awt.Color(255, 255, 255));
        jVPrecio.setBorder(null);
        jVPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jVPrecioMouseClicked(evt);
            }
        });
        jVPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVPrecioActionPerformed(evt);
            }
        });
        jVPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jVPrecioKeyTyped(evt);
            }
        });
        jPanel5.add(jVPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 150, -1));

        jCodigo.setBackground(new java.awt.Color(0, 0, 0));
        jCodigo.setFont(new java.awt.Font("Thames", 0, 16)); // NOI18N
        jCodigo.setForeground(new java.awt.Color(255, 255, 255));
        jCodigo.setBorder(null);
        jCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCodigoActionPerformed(evt);
            }
        });
        jPanel5.add(jCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 80, -1));
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 150, 10));
        jPanel5.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 150, 10));
        jPanel5.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 150, 10));

        jVCantidad.setBackground(new java.awt.Color(0, 0, 0));
        jVCantidad.setFont(new java.awt.Font("Thames", 0, 16)); // NOI18N
        jVCantidad.setForeground(new java.awt.Color(255, 255, 255));
        jVCantidad.setBorder(null);
        jVCantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jVCantidadMouseClicked(evt);
            }
        });
        jVCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVCantidadActionPerformed(evt);
            }
        });
        jVCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jVCantidadKeyTyped(evt);
            }
        });
        jPanel5.add(jVCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 150, -1));
        jPanel5.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 80, 10));

        jLabel5.setFont(new java.awt.Font("Thames", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("GENERAR VÁLVULAS");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jAñadirV.setFont(new java.awt.Font("Thames", 0, 16)); // NOI18N
        jAñadirV.setForeground(new java.awt.Color(255, 255, 255));
        jAñadirV.setText("Añadir");
        jAñadirV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAñadirVMouseClicked(evt);
            }
        });
        jPanel5.add(jAñadirV, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, -1));
        jPanel5.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 50, 10));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Generar", jPanel4);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Thames", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("EDITAR VÁLVULAS");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ValvulaRetenedora.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel10.setFont(new java.awt.Font("Thames", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Referencia:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        jLabel11.setFont(new java.awt.Font("Thames", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cantidad:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        jLabel12.setFont(new java.awt.Font("Thames", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Precio:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        CantidadEdit.setBackground(new java.awt.Color(0, 0, 0));
        CantidadEdit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CantidadEdit.setForeground(new java.awt.Color(255, 255, 255));
        CantidadEdit.setBorder(null);
        CantidadEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadEditActionPerformed(evt);
            }
        });
        jPanel2.add(CantidadEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 150, -1));

        PrecioEdit.setBackground(new java.awt.Color(0, 0, 0));
        PrecioEdit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PrecioEdit.setForeground(new java.awt.Color(255, 255, 255));
        PrecioEdit.setBorder(null);
        PrecioEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioEditActionPerformed(evt);
            }
        });
        jPanel2.add(PrecioEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 150, -1));

        RefeEditar.setBackground(new java.awt.Color(0, 0, 0));
        RefeEditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RefeEditar.setForeground(new java.awt.Color(255, 255, 255));
        RefeEditar.setBorder(null);
        RefeEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefeEditarActionPerformed(evt);
            }
        });
        jPanel2.add(RefeEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 150, -1));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 150, -1));
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 150, 10));
        jPanel2.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 150, 10));

        jEditanBtn.setFont(new java.awt.Font("Thames", 0, 14)); // NOI18N
        jEditanBtn.setForeground(new java.awt.Color(255, 255, 255));
        jEditanBtn.setText("Editar");
        jEditanBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEditanBtnMouseClicked(evt);
            }
        });
        jPanel2.add(jEditanBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 237, -1, 10));
        jPanel2.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 40, 10));

        javax.swing.GroupLayout jEditarPanelLayout = new javax.swing.GroupLayout(jEditarPanel);
        jEditarPanel.setLayout(jEditarPanelLayout);
        jEditarPanelLayout.setHorizontalGroup(
            jEditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jEditarPanelLayout.setVerticalGroup(
            jEditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Editar", jEditarPanel);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jVRevisar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Referencia", "Precio", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(jVRevisar);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 310));

        javax.swing.GroupLayout jRevisarPanelLayout = new javax.swing.GroupLayout(jRevisarPanel);
        jRevisarPanel.setLayout(jRevisarPanelLayout);
        jRevisarPanelLayout.setHorizontalGroup(
            jRevisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jRevisarPanelLayout.setVerticalGroup(
            jRevisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Revisar", jRevisarPanel);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 580, 340));

        JNavegador.setBackground(new java.awt.Color(0, 0, 0));
        JNavegador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInicio1.setFont(new java.awt.Font("Thames", 0, 18)); // NOI18N
        jInicio1.setForeground(new java.awt.Color(255, 255, 255));
        jInicio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jInicio1.setText("Inicio");
        jInicio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jInicio1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jInicio1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jInicio1MouseExited(evt);
            }
        });
        JNavegador.add(jInicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 50, -1));
        JNavegador.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 50, -1));

        jPersonas.setFont(new java.awt.Font("Thames", 0, 16)); // NOI18N
        jPersonas.setForeground(new java.awt.Color(255, 255, 255));
        jPersonas.setText("Personas");
        jPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPersonasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPersonasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPersonasMouseExited(evt);
            }
        });
        JNavegador.add(jPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jFacturas.setFont(new java.awt.Font("Thames", 0, 16)); // NOI18N
        jFacturas.setForeground(new java.awt.Color(255, 255, 255));
        jFacturas.setText("Facturas");
        jFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFacturasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jFacturasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jFacturasMouseExited(evt);
            }
        });
        JNavegador.add(jFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));
        JNavegador.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 60, -1));
        JNavegador.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 60, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ValvulaBásica.png"))); // NOI18N
        JNavegador.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, -1, 90));

        jPanel1.add(JNavegador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 580, 80));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondonegro.jpg"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jExitMouseClicked

    private void jExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExitMouseEntered
        jExit.setForeground(Color.red);
    }//GEN-LAST:event_jExitMouseEntered

    private void jExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExitMouseExited
        jExit.setForeground(Color.white);
    }//GEN-LAST:event_jExitMouseExited

    private void jVNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jVNombreActionPerformed

    private void jCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCodigoActionPerformed

    private void jVCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jVCantidadActionPerformed

    private void jInicio1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInicio1MouseClicked
        Intro intro = new Intro();
        intro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jInicio1MouseClicked

    private void jInicio1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInicio1MouseEntered
        jInicio1.setForeground(Color.cyan);
    }//GEN-LAST:event_jInicio1MouseEntered

    private void jInicio1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInicio1MouseExited
        jInicio1.setForeground(Color.white);
    }//GEN-LAST:event_jInicio1MouseExited

    private void jPersonasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPersonasMouseEntered
        jPersonas.setForeground(Color.red);
    }//GEN-LAST:event_jPersonasMouseEntered

    private void jPersonasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPersonasMouseExited
        jPersonas.setForeground(Color.white);
    }//GEN-LAST:event_jPersonasMouseExited

    private void jFacturasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFacturasMouseEntered
        jFacturas.setForeground(Color.red);
    }//GEN-LAST:event_jFacturasMouseEntered

    private void jFacturasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFacturasMouseExited
        jFacturas.setForeground(Color.white);
    }//GEN-LAST:event_jFacturasMouseExited

    private void jPersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPersonasMouseClicked
        jCrear personas = new jCrear();
        personas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPersonasMouseClicked
    private void llenarFormulario(int IdMod){
        ListaValvulas objetoLista = new ListaValvulas();
    }
    private void jAñadirVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAñadirVMouseClicked
        if (jVNombre.getText().isBlank() || jVPrecio.getText().isBlank() || jVCantidad.getText().isBlank() || jCodigo.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "");
        }else{
         String nombre = this.jVNombre.getText();
        int precio = Integer.parseInt(this.jVPrecio.getText());
        int cantidad = Integer.parseInt(this.jVCantidad.getText());
        int id = Integer.parseInt(this.jCodigo.getText());
        
        ListaValvulas listaValvulas = new ListaValvulas();
        
        listaValvulas.agregarValvula(id, nombre, precio, cantidad);
        
        this.jCodigo.setText(null);
        this.jVNombre.setText(null);
        this.jVPrecio.setText(null);
        this.jVPrecio.setText(null);
        
        llenarTabla(listaValvulas.getLista());
        limpiar();   
        } 
    }//GEN-LAST:event_jAñadirVMouseClicked
    
    private void jVPrecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jVPrecioMouseClicked
        
    }//GEN-LAST:event_jVPrecioMouseClicked

    private void jVCantidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jVCantidadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jVCantidadMouseClicked

    private void jVPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jVPrecioKeyTyped
        char car;
        car = evt.getKeyChar();
        if((car<'0' || car>'9') && car!=(char)KeyEvent.VK_BACK_SPACE){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo se admiten números","Validar información",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jVPrecioKeyTyped

    private void jVCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jVCantidadKeyTyped
        char car;
        car = evt.getKeyChar();
        if((car<'0' || car>'9') && car!=(char)KeyEvent.VK_BACK_SPACE){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo se admiten números","Validar información",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jVCantidadKeyTyped

    private void jVNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jVNombreKeyTyped

    }//GEN-LAST:event_jVNombreKeyTyped

    private void jVPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jVPrecioActionPerformed

    private void jFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFacturasMouseClicked
        jFactura ventana = new jFactura();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jFacturasMouseClicked

    private void CantidadEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadEditActionPerformed

    private void PrecioEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioEditActionPerformed

    private void RefeEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefeEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RefeEditarActionPerformed

    private void jEditanBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEditanBtnMouseClicked
        
    }//GEN-LAST:event_jEditanBtnMouseClicked
    private void llenarTabla(ArrayList<Valvula> eLista){
        DefaultTableModel modelo = (DefaultTableModel) this.jVRevisar.getModel();
        
        for (Valvula fila : eLista) {
            modelo.addRow(new Object[]{fila.getCodigo(),fila.getNombre(),fila.getPrecio(),fila.getCantidad()});
            
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CantidadEdit;
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel JNavegador;
    private javax.swing.JTextField PrecioEdit;
    private javax.swing.JTextField RefeEditar;
    private javax.swing.JLabel jAñadirV;
    private javax.swing.JTextField jCodigo;
    private javax.swing.JLabel jEditanBtn;
    private javax.swing.JPanel jEditarPanel;
    private javax.swing.JLabel jExit;
    private javax.swing.JLabel jFacturas;
    private javax.swing.JLabel jInicio1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jPersonas;
    private javax.swing.JPanel jRevisarPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jVCantidad;
    private javax.swing.JTextField jVNombre;
    private javax.swing.JTextField jVPrecio;
    private javax.swing.JTable jVRevisar;
    // End of variables declaration//GEN-END:variables

    private void limpiar() {
        jVNombre.setText(null);
        jVCantidad.setText(null);
        jVPrecio.setText(null);
        jCodigo.setText(null);
    }
}